In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import pandas as pd

In [5]:
tabela = pd.read_csv("/content/drive/MyDrive/DB's/mundo_transfermarkt_competicoes_brasileirao_serie_a.csv.gz")
display(tabela)

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_mandante,time_visitante,tecnico_mandante,...,chutes_bola_parada_mandante,chutes_bola_parada_visitante,defesas_mandante,defesas_visitante,impedimentos_mandante,impedimentos_visitante,chutes_mandante,chutes_visitante,chutes_fora_mandante,chutes_fora_visitante
0,2005,2005-10-08,31,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Fluminense,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005,2005-04-23,1,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Goiás EC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005,2005-08-21,21,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Vasco da Gama,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005,2005-08-28,23,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,São Paulo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005,2005-06-26,9,Estádio Olímpico Nilton Santos,NaN,NaN,NaN,Botafogo,Figueirense FC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8448,2017,2017-10-15,28,Estádio Municipal Paulo Machado de Carvalho,Marcelo de Lima Henrique,26833.0,37730.0,São Paulo,Atlético-PR,Dorival Júnior,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8449,2017,2017-10-22,30,Estádio Municipal Paulo Machado de Carvalho,Rafael Traci,32965.0,37730.0,São Paulo,Flamengo,Dorival Júnior,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8450,2017,2017-10-28,31,Estádio Municipal Paulo Machado de Carvalho,Anderson Daronco,40004.0,40500.0,São Paulo,Santos FC,Dorival Júnior,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8451,2017,2017-11-09,33,Estádio Municipal Paulo Machado de Carvalho,Marcelo de Lima Henrique,35037.0,37730.0,São Paulo,Chapecoense,Dorival Júnior,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8452,2017,2017-11-19,36,Estádio Municipal Paulo Machado de Carvalho,Wilton Sampaio,25771.0,37730.0,São Paulo,Botafogo,Dorival Júnior,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
display(tabela.info())
display(tabela.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8453 entries, 0 to 8452
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ano_campeonato                  8453 non-null   int64
 1   data                            8453 non-null   object
 2   rodada                          8453 non-null   int64
 3   estadio                         8442 non-null   object
 4   arbitro                         6743 non-null   object
 5   publico                         6742 non-null   float64
 6   publico_max                     4181 non-null   float64
 7   time_mandante                   8453 non-null   object
 8   time_visitante                  8453 non-null   object
 9   tecnico_mandante                6299 non-null   object
 10  tecnico_visitante               6299 non-null   object
 11  colocacao_mandante              6743 non-null   float64
 12  colocacao_visitante             6743 non-null   float64
 13  valor_equipe_titular_mandante   6355 non-null   float64
 14  valor_equipe_titular_visitante  6355 non-null   float64
 15  idade_media_titular_mandante    6353 non-null   float64
 16  idade_media_titular_visitante   6353 non-null   float64
 17  gols_mandante                   8452 non-null   float64
 18  gols_visitante                  8452 non-null   float64
 19  gols_1_tempo_mandante           6732 non-null   float64
 20  gols_1_tempo_visitante          6732 non-null   float64
 21  escanteios_mandante             2087 non-null   float64
 22  escanteios_visitante            2087 non-null   float64
 23  faltas_mandante                 2087 non-null   float64
 24  faltas_visitante                2087 non-null   float64
 25  chutes_bola_parada_mandante     2087 non-null   float64
 26  chutes_bola_parada_visitante    2087 non-null   float64
 27  defesas_mandante                2087 non-null   float64
 28  defesas_visitante               2087 non-null   float64
 29  impedimentos_mandante           2087 non-null   float64
 30  impedimentos_visitante          2087 non-null   float64
 31  chutes_mandante                 2087 non-null   float64
 32  chutes_visitante                2087 non-null   float64
 33  chutes_fora_mandante            2087 non-null   float64
 34  chutes_fora_visitante           2087 non-null   float64
dtypes: float64(26), int64(2), object(7)
memory usage: 2.3+ MB

None

,ano_campeonato,rodada,publico,publico_max,colocacao_mandante,colocacao_visitante,valor_equipe_titular_mandante,valor_equipe_titular_visitante,idade_media_titular_mandante,idade_media_titular_visitante,...,chutes_bola_parada_mandante,chutes_bola_parada_visitante,defesas_mandante,defesas_visitante,impedimentos_mandante,impedimentos_visitante,chutes_mandante,chutes_visitante,chutes_fora_mandante,chutes_fora_visitante
count,8453.000000,8453.000000,6742.000000,4181.000000,6743.000000,6743.000000,6.355000e+03,6.355000e+03,6353.000000,6353.000000,...,2087.000000,2087.000000,2087.000000,2087.000000,2087.000000,2087.00000,2087.000000,2087.000000,2087.000000,2087.000000
mean,2013.161481,19.386490,16189.951943,43910.461373,10.617084,10.384992,1.615418e+07,1.575332e+07,27.309869,27.211727,...,13.724964,14.068999,2.834691,3.544322,1.514135,1.42597,13.151893,10.256828,6.022520,4.650695
std,6.368650,10.924158,14074.412391,19838.986238,5.761853,5.770435,1.471446e+07,1.410733e+07,1.619763,1.655798,...,4.406922,4.390899,1.869671,2.151016,1.417487,1.33043,6.095550,5.245020,2.849193,2.538709
min,2003.000000,1.000000,0.000000,5000.000000,1.000000,1.000000,5.600000e+02,4.430000e+02,20.400000,20.500000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,2008.000000,10.000000,5898.250000,24584.000000,6.000000,5.000000,5.850000e+06,5.800000e+06,26.200000,26.100000,...,11.000000,11.000000,1.000000,2.000000,0.000000,0.00000,9.000000,6.000000,4.000000,3.000000
50%,2013.000000,19.000000,12685.500000,43600.000000,11.000000,10.000000,1.170000e+07,1.165000e+07,27.300000,27.200000,...,13.000000,14.000000,3.000000,3.000000,1.000000,1.00000,13.000000,10.000000,6.000000,4.000000
75%,2019.000000,29.000000,22963.250000,57483.000000,16.000000,15.000000,2.360000e+07,2.300000e+07,28.400000,28.300000,...,16.000000,17.000000,4.000000,5.000000,2.000000,2.00000,17.000000,14.000000,8.000000,6.000000
max,2024.000000,38.000000,82044.000000,87101.000000,20.000000,20.000000,1.005000e+08,9.600000e+07,33.600000,33.100000,...,30.000000,30.000000,12.000000,13.000000,9.000000,8.00000,37.000000,31.000000,21.000000,14.000000

In [8]:
qtd_pessoas = tabela["publico"].value_counts()
display(qtd_pessoas)

time = tabela["time_mandante"].value_counts()
display(time)

publico
0.0        858
32157.0      9
12089.0      5
9525.0       4
17784.0      3
          ...
8142.0       1
19469.0      1
39060.0      1
22708.0      1
15096.0      1
Name: count, Length: 5408, dtype: int64

time_mandante
Flamengo          414
São Paulo         414
Fluminense        413
Corinthians       394
Atlético-MG       394
Internacional     392
Grêmio            376
Palmeiras         375
Cruzeiro          357
Botafogo          356
Santos FC         342
Vasco da Gama     318
Coritiba FC       285
Atlético-PR       285
Goiás EC          248
EC Bahia          223
Figueirense FC    209
Sport Recife      209
EC Vitória        205
Ponte Preta       171
Fortaleza         167
Juventude         147
Atlético-GO       147
Ceará SC          133
Chapecoense       133
Avaí FC           133
Paraná            114
América-MG        114
Athletico-PR      108
Náutico            95
Criciúma EC        90
RB Bragantino      89
São Caetano        76
Cuiabá-MT          71
Paysandu SC        57
Santos             57
Portuguesa         57
Guarani            57
Santa Cruz         38
Barueri            38
Goiás              38
Brasiliense-DF     19
Joinville-SC       19
Santo André        19
Ipatinga FC        19
CSA                19
América-RN         19
Name: count, dtype: int64

In [9]:
import plotly.express as plt

grafico_pub = plt.histogram(tabela, x="time_mandante", y="publico" )
display(grafico_pub)

In [10]:
grafico_golsFora = plt.histogram(tabela, x="time_visitante", y="gols_visitante" )
display(grafico_golsFora)

# Flamengo, São Paulo e Fluminense são muito fortes fora de casa, levando em conta o histórico

In [11]:
grafico_golsCasa = plt.histogram(tabela, x = "time_mandante", y = "gols_mandante")
display(grafico_golsCasa)

# São Paulo, Flamengo, Atlético-MG, Palmeiras, Grêmio são muito fortes dentro de casa, tendo maior probabilidade de vitória

In [12]:
grafico_escanteioCasa = plt.histogram(tabela, x = "time_mandante", y = "escanteios_mandante")
display(grafico_escanteioCasa)

# Palmeiras e Flamengo chamam atenção na quantidade de escanteios dentro de casa

In [13]:
grafico_escanteioFora = plt.histogram(tabela, x="time_visitante", y = "escanteios_visitante")
display(grafico_escanteioFora)

# Atlético Mineiro e Palmeiras tem muitos escanteios fora de casa

In [15]:
grafico_faltaFora = plt.histogram(tabela, x="time_visitante", y="faltas_visitante")
display(grafico_faltaFora)

# O palmeiras faz muita falta fora de casa

In [16]:
grafico_faltaCasa = plt.histogram(tabela, x="time_mandante", y="faltas_mandante")
display(grafico_faltaCasa)

# O Internacional, Altético Mineiro, Athlético Paranaense, Fluminense fazem muita falta dentro de casa.

# O que é possível perceber com a análise:
 * Flamengo, São Paulo e Fluminense possuem maior chance de marcar gols fora de casa
 * São Paulo, Flamengo, Atlético-MG, Palmeiras, Grêmio são fortes dentro de casa
 * Palmeiras e Flamengo são fortes em escanteios dentro de casa
 * Atlético Mineiro e Palmeiras tem muitos escanteios fora de casa
 * Palmeiras tem muita falta fora de casa
 * O Internacional, Altético Mineiro, Athlético Paranaense, Fluminense fazem muita falta dentro de casa.